# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggy', '0002_posts_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
