# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggy', '0004_auto_20160121_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
