# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggy', '0005_auto_20160121_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='users',
        ),
    ]
